# 客户端版本更新配置
# 服务每30秒检查此文件是否有修改，如有修改则自动重新加载

# Android 版本配置
version.android.latestVersion=1.3.0
version.android.buildNumber=130
version.android.minVersion=1.0.0
version.android.forceUpdate=false
version.android.title=发现新版本
version.android.message=1. 优化性能\n2. 修复已知问题
## Example: https://download.example.com/chat-latest.apk
version.android.downloadUrl=https://static.wildfirechat.cn/chat-release-latest.apk

# iOS 版本配置
version.ios.latestVersion=1.3.0
version.ios.buildNumber=130
version.ios.minVersion=1.0.0
version.ios.forceUpdate=false
version.ios.title=发现新版本
version.ios.message=1. 优化性能\n2. 修复已知问题
## Example: itms-apps://itunes.apple.com/us/app/XXCHAT/id1234567?ls=1&mt=8
version.ios.redirectUrl=itms-apps://itunes.apple.com/us/app/野火IM/id1450256455?ls=1&mt=8

# 鸿蒙 HarmonyOS 版本配置
version.harmony.latestVersion=1.3.0
version.harmony.buildNumber=130
version.harmony.minVersion=1.0.0
version.harmony.forceUpdate=false
version.harmony.title=发现新版本
version.harmony.message=1. 优化性能\n2. 修复已知问题
## Example: store://appgallery.huawei.com/app/detail?id=com.example.XXChat
version.harmony.harmonyUrl=store://appgallery.huawei.com/app/detail?id=cn.wildfirechat.messenger
